(function(){
'use strict';
const $=id=>document.getElementById(id);
const status=$('status'), run=$('run'), fileInput=$('file'), drop=$('drop');
let file=null;
const {jsPDF}=window.jspdf||{};
if(!window.pdfjsLib||!jsPDF){status.textContent='Library belum termuat. Refresh halaman atau periksa koneksi internet.';return;}
pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js';
const outputs=[['noise','noiseOut','%'],['warp','warpOut',' mm'],['sigSize','sigSizeOut','%'],['sigX','sigXOut','%'],['sigY','sigYOut','%'],['stkSize','stkSizeOut','%'],['stkX','stkXOut','%'],['stkY','stkYOut','%']];
outputs.forEach(([a,b,s])=>$(a).addEventListener('input',()=>$(b).textContent=$(a).value+s));
function setFile(f){if(!f)return;if(!/\.(pdf|docx)$/i.test(f.name)){status.textContent='File harus PDF atau DOCX.';return;}file=f;$('name').textContent=f.name;run.disabled=false;$('download').hidden=true;status.textContent='File siap diproses: '+f.name;}
fileInput.addEventListener('change',e=>{if(e.target.files&&e.target.files[0])setFile(e.target.files[0]);});
['dragenter','dragover'].forEach(ev=>drop.addEventListener(ev,e=>{e.preventDefault();e.stopPropagation();drop.classList.add('drag');}));
['dragleave','drop'].forEach(ev=>drop.addEventListener(ev,e=>{e.preventDefault();e.stopPropagation();drop.classList.remove('drag');}));
drop.addEventListener('drop',e=>{const f=e.dataTransfer.files&&e.dataTransfer.files[0];if(f)setFile(f);});
function rng(seed){let x=(seed>>>0)||1;return()=>{x^=x<<13;x^=x>>>17;x^=x<<5;return(x>>>0)/4294967296;};}
function pageSet(text,n){text=(text||'all').trim().toLowerCase();if(!text||text==='all')return true;return text.split(',').map(x=>parseInt(x.trim(),10)).includes(n);}
function readImage(f){return new Promise((res,rej)=>{const u=URL.createObjectURL(f),im=new Image();im.onload=()=>{URL.revokeObjectURL(u);res(im)};im.onerror=e=>{URL.revokeObjectURL(u);rej(e)};im.src=u;});}
function addImageTransform(ctx,img,cx,cy,w,h,kind,r){ctx.save();ctx.translate(cx,cy);if(kind==='sticker'){ctx.rotate((r()*6-3)*Math.PI/180);}else{const p=(r()*6-3)/100,q=(r()*6-3)/100;const mode=Math.floor(r()*3);if(mode===0)ctx.scale(1+p,1+q);else if(mode===1)ctx.transform(1,0,p,1,0,0);else ctx.transform(1,q,p,1,0,0);}ctx.globalAlpha=.96;ctx.drawImage(img,-w/2,-h/2,w,h);ctx.restore();}
function addOverlays(c,sig,stk,pageNo,r){const ctx=c.getContext('2d');if(sig&&pageSet($('sigPages').value,pageNo)){const w=c.width*(+$('sigSize').value/100),ar=sig.naturalWidth/sig.naturalHeight;addImageTransform(ctx,sig,c.width*(+$('sigX').value/100),c.height*(+$('sigY').value/100),w,w/ar,'signature',r);}if(stk&&pageSet($('stkPages').value,pageNo)){const w=c.width*(+$('stkSize').value/100),ar=stk.naturalWidth/stk.naturalHeight;addImageTransform(ctx,stk,c.width*(+$('stkX').value/100),c.height*(+$('stkY').value/100),w,w/ar,'sticker',r);}}
function distort(src,mm,dpi,r){if(mm<=0)return src;const w=src.width,h=src.height,px=mm*dpi/25.4,out=document.createElement('canvas');out.width=w;out.height=h;const ctx=out.getContext('2d');ctx.fillStyle='rgb(245,245,242)';ctx.fillRect(0,0,w,h);const strips=120;const L=[(r()*2-1)*px,(r()*2-1)*px],R=[(r()*2-1)*px,(r()*2-1)*px],BL=[(r()*2-1)*px,(r()*2-1)*px],BR=[(r()*2-1)*px,(r()*2-1)*px];for(let i=0;i<strips;i++){const t=i/(strips-1),y=i*h/strips,sh=h/strips+1,lx=L[0]*(1-t)+BL[0]*t,rx=R[0]*(1-t)+BR[0]*t;ctx.save();ctx.beginPath();ctx.rect(0,y,w,sh);ctx.clip();ctx.translate(lx,0);ctx.drawImage(src,0,y,w,sh,0,y,w,sh);ctx.restore();}return out;}
function addNoise(c,amount,r){const ctx=c.getContext('2d'),n=Math.round(c.width*c.height/28000*(amount/25));for(let i=0;i<n;i++){const x=r()*c.width,y=r()*c.height,z=r()<.82?1:2,a=(8+r()*14)/255,g=90+r()*85;ctx.fillStyle=`rgba(${g},${g},${g},${a})`;ctx.beginPath();ctx.arc(x,y,z,0,Math.PI*2);ctx.fill();}}
async function pdfPages(f,dpi){const data=await f.arrayBuffer(),pdf=await pdfjsLib.getDocument({data}).promise,pages=[];for(let i=1;i<=pdf.numPages;i++){const p=await pdf.getPage(i),v=p.getViewport({scale:dpi/72}),c=document.createElement('canvas');c.width=Math.ceil(v.width);c.height=Math.ceil(v.height);await p.render({canvasContext:c.getContext('2d'),viewport:v}).promise;pages.push(c);}return pages;}
async function docxPages(f){if(!window.docx||!window.html2canvas)throw new Error('Library DOCX belum termuat.');const host=document.createElement('div');host.style.cssText='position:fixed;left:-100000px;top:0;width:794px;background:white;z-index:-1';document.body.appendChild(host);await window.docx.renderAsync(await f.arrayBuffer(),host,null,{breakPages:true,ignoreWidth:false,ignoreHeight:false});const nodes=[...host.querySelectorAll('section.docx')];if(!nodes.length)throw new Error('DOCX tidak dapat dirender di browser.');const canv=[];for(const n of nodes)canv.push(await html2canvas(n,{backgroundColor:'#fff',scale:1,useCORS:true}));host.remove();return canv;}
run.addEventListener('click',async()=>{if(!file)return;run.disabled=true;$('download').hidden=true;try{const dpi=+$('dpi').value||96,noise=+$('noise').value,warp=+$('warp').value;let seed=+$('seed').value;if(!Number.isFinite(seed))seed=Math.floor(Math.random()*2147483647);const r=rng(seed);const sig=$('signature').files[0]?await readImage($('signature').files[0]):null;const stk=$('sticker').files[0]?await readImage($('sticker').files[0]):null;status.textContent='Membaca file…';let pages=/\.pdf$/i.test(file.name)?await pdfPages(file,dpi):await docxPages(file);let out=null;for(let i=0;i<pages.length;i++){status.textContent=`Memproses halaman ${i+1} dari ${pages.length}…`;let c=pages[i];if(/\.pdf$/i.test(file.name)){const toned=document.createElement('canvas');toned.width=c.width;toned.height=c.height;const t=toned.getContext('2d');t.fillStyle='#fff';t.fillRect(0,0,c.width,c.height);t.drawImage(c,0,0);c=toned;}addOverlays(c,sig,stk,i+1,r);const d=distort(c,warp,dpi,r);addNoise(d,noise,r);const ori=d.width>=d.height?'landscape':'portrait';if(!out)out=new jsPDF({orientation:ori,unit:'px',format:[d.width,d.height],compress:true});else out.addPage([d.width,d.height],ori);out.addImage(d.toDataURL('image/jpeg',.94),'JPEG',0,0,d.width,d.height);}if(!out)throw new Error('Tidak ada halaman yang berhasil diproses.');const blob=out.output('blob'),url=URL.createObjectURL(blob),base=file.name.replace(/\.[^.]+$/,'');const a=$('download');a.href=url;a.download=base+'_FIN.pdf';a.textContent=`Download ${base}_FIN.pdf`;a.hidden=false;status.textContent=`Selesai. ${pages.length} halaman diproses.`;}catch(e){console.error(e);status.textContent='Gagal: '+(e&&e.message?e.message:e);}finally{run.disabled=false;}});
})();
