import * as pdfjsLib from "https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.min.mjs";
pdfjsLib.GlobalWorkerOptions.workerSrc="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.worker.min.mjs";
const {jsPDF}=window.jspdf; const $=id=>document.getElementById(id); let file=null;
$('file').onchange=e=>{file=e.target.files[0];$('name').textContent=file?.name||'';$('run').disabled=!file};
$('noise').oninput=()=>$('noiseOut').textContent=$('noise').value+'%';$('warp').oninput=()=>$('warpOut').textContent=$('warp').value+' mm';
function rng(seed){let x=seed>>>0;return()=>{x^=x<<13;x^=x>>>17;x^=x<<5;return(x>>>0)/4294967296}}
function distort(src,mm,dpi,r){const w=src.width,h=src.height,px=mm*dpi/25.4,c=document.createElement('canvas');c.width=w;c.height=h;const ctx=c.getContext('2d');ctx.fillStyle='#f5f5f2';ctx.fillRect(0,0,w,h);const strips=100;const top=[(r()*2-1)*px,(r()*2-1)*px],tr=[(r()*2-1)*px,(r()*2-1)*px],bot=[(r()*2-1)*px,(r()*2-1)*px],br=[(r()*2-1)*px,(r()*2-1)*px];for(let i=0;i<strips;i++){let t=i/strips,t2=(i+1)/strips,ly=top[0]*(1-t)+bot[0]*t,ry=tr[0]*(1-t)+br[0]*t;ctx.save();ctx.beginPath();ctx.rect(0,i*h/strips,w,h/strips+1);ctx.clip();ctx.setTransform(1+(ry-ly)/w,0,0,1,ly,0);ctx.drawImage(src,0,i*h/strips,w,h/strips,0,i*h/strips,w,h/strips);ctx.restore()}return c}
function noise(c,amount,r){const ctx=c.getContext('2d'),n=Math.max(0,Math.round(c.width*c.height/28000*amount/25));for(let i=0;i<n;i++){let x=r()*c.width,y=r()*c.height,z=r()<.8?1:2,a=(8+r()*14)/255,g=90+r()*85;ctx.fillStyle=`rgba(${g},${g},${g},${a})`;ctx.beginPath();ctx.arc(x,y,z,0,7);ctx.fill()}}
$('run').onclick=async()=>{if(!file)return;$('run').disabled=true;try{let seed=Date.now(),r=rng(seed),pdf=await pdfjsLib.getDocument({data:await file.arrayBuffer()}).promise,out=null;for(let i=1;i<=pdf.numPages;i++){ $('status').textContent=`Memproses ${i}/${pdf.numPages}...`;let p=await pdf.getPage(i),v=p.getViewport({scale:(+$('dpi').value||96)/72}),c=document.createElement('canvas');c.width=Math.ceil(v.width);c.height=Math.ceil(v.height);await p.render({canvasContext:c.getContext('2d'),viewport:v}).promise;let d=distort(c,+$('warp').value,+$('dpi').value,r);noise(d,+$('noise').value,r);let ori=v.width>=v.height?'landscape':'portrait';if(!out)out=new jsPDF({orientation:ori,unit:'px',format:[d.width,d.height],compress:true});else out.addPage([d.width,d.height],ori);out.addImage(d.toDataURL('image/jpeg',.94),'JPEG',0,0,d.width,d.height)}let url=URL.createObjectURL(out.output('blob')),base=file.name.replace(/\.[^.]+$/,'');$('download').href=url;$('download').download=base+'_FIN.pdf';$('download').textContent='Download '+base+'_FIN.pdf';$('download').hidden=false;$('status').textContent='Selesai.'}catch(e){$('status').textContent='Gagal: '+e.message;console.error(e)}finally{$('run').disabled=false}};
